server:
  port: 8004

# bus
management:
  endpoints:
    web:
      exposure:
        include: "*"
#七牛
qiniu:
  accessKey: psM0ckGREV6Qh-a0xKprtuPwJRk5mzLEtoT11jbw
  secretKey: IJ7o66mVQfCHuxRtoIs82nK1egLuXR9BrMsJy4D_
  bucketName: shop-wxq
  qiniuImageDomain: http://qtd0yoo30.hn-bkt.clouddn.com/

spring:
  profiles:
    active: dev
